all: TW

TW: main.cpp WavetableOsc.cpp
	g++ -std=c++11 -o testwav mainEnum.cpp WavetableOsc.cpp

TWold: main.cpp WavetableOsc.cpp
		g++ -std=c++11 -o testwav main.cpp WavetableOsc.cpp

clean:
	rm -f TW TW2
